apiVersion: v1
kind: Pod
metadata:
  name: java-tools
  #namespace: default
spec:
  containers:
  - args:
    command:
    - /usr/bin/sleep
    - "100000"
    image: sfbrdevhelmweacr.azurecr.io/sf-java-tools:v0.1
    imagePullPolicy: Always
    name: dntracer
    resources: {}
    securityContext:
      privileged: true
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-bgntv
      readOnly: true
    - mountPath: /host
      name: host
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostPID: true
  hostNetwork: true
  hostIPC: true
  # nodeName: server0
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 30
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 30
  volumes:
  - hostPath:
      path: /
      type: ""
    name: host
  - name: kube-api-access-bgntv
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace